### ISSUE TITLE
The "importFile" argument does not exist

### ISSUE THREAD

**Issue by asherry** [Pr0ject-X/px-ddev#1]

**Comment by asherry** [comment]
I'm getting this error when I try to run px pantheon:sync with ddev. I had this issue before with platformsh:sync, I think there was an update with px where the argument changed.

I have some code I'll put it in a PR.

```4/4 [============================] 100%
 [SymfonyCommand] Running command db:import
 [CompletionWrapper]  The "importFile" argument does not exist.
 [CompletionWrapper]  Exit code 1```

**Comment by droath** [comment]
@asherry The ddev px plugin has been reworked so it should work as expected now.
